### ISSUE TITLE
Create /etc/cyhy/cyhy.conf in multiple roles

### ISSUE THREAD

**Issue by KyleEvers** [cisagov/cyhy_amis#129]
We create `/etc/cyhy/cyhy.conf` in multiple roles, such as feeds and commander, which is redundant and could cause potential errors when both roles are applied to the same instance.  

See [here](https://github.com/dhs-ncats/cyhy_amis/pull/128#discussion_r225545701) for details.

**Comment by dav3r** [comment]
Closed by PR #161
