### ISSUE TITLE
Nessus Ansible Role Will Always Stop Nessus Service

### ISSUE THREAD

**Issue by mcdonnnj** [cisagov/cyhy_amis#236]
# 🐛 Bug Report

Whenever a provisioner runs the `nessus` role the given playbook will always stop the Nessus service on the AWS instance. This would result in unnecessary downtime and delays for scans, as all in progress scans are aborted and any results are discarded if the service is stopped.

["If the Nessus instance restarts or if the service is stopped, all scan jobs will abort and the results will be discarded."](https://community.tenable.com/s/article/What-happens-if-Nessus-or-the-target-reboots-in-the-middle-of-an-active-scan)

## To Reproduce

Perform a Terraform apply that results in a provisioner running the `nessus` Ansible role.

## Expected behavior

The Nessus service should only be stopped if there is no key registered, or if the key registered does not match the key to be used. That way the service is only stopped on initial instance setup or if the key is being changed.

**Comment by mcdonnnj** [comment]
This should be resolved by #239

**Comment by dav3r** [comment]
Excellent work @mcdonnnj - thanks! 🎡
