### ISSUE TITLE
Code in terraform_egress_pub directory does not publish COOL IPs

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cyhy_amis#284]
# 🐛 Bug Report

We claim that [the rules site](https://rules.ncats.cyber.dhs.gov/all.txt) "contains a consolidated list of all the IP addresses that VM is currently using for external scanning," but this is not true.  The list does not contain any scanning IPs from the COOL.  As a result, I propose that this Terraform code:
1. Be broken out into its own repository
1. Include scanning IPs from _all_ AWS accounts that VM uses

See also:
* #308
* #309

## Expected behavior

[The rules site](https://rules.ncats.cyber.dhs.gov/all.txt) should indeed "[contain] a consolidated list of all the IP addresses that VM is currently using for external scanning".

**Comment by jsf9k** [comment]
@dav3r pointed out that we may not want to publish _all_ our AWS scanning IPs.  Some assessment types may not want this.  The assessment types currently broken out into individual lists are:
* CyHy (cyber hygiene)
* PCA (phishing campaign assessment)
* WAS (web application scanning)

I was particularly thinking of the PCA teamserver IPs that we currently publish.  That functionality will eventually move to the COOL, and folks will presumably continue looking for those IPs here.

**Comment by jsf9k** [comment]
It may make sense to [let Lambda@Edge compile the list of IPs](https://github.com/cisagov/cyhy_amis/issues/308#issuecomment-761585430).

**Comment by dav3r** [comment]
This issue can be closed because the desired functionality has been implemented elsewhere.  Please see the following for more information:
- https://github.com/cisagov/cool-system-internal/issues/125
- https://github.com/cisagov/publish-egress-ip-lambda/pull/4
- https://github.com/cisagov/publish-egress-ip-terraform/pull/6
