### ISSUE TITLE
Update Terraform Code for Terraform 0.13

### ISSUE THREAD

**Issue by mcdonnnj** [cisagov/cyhy_amis#297]
# 🚀 Feature Proposal

With [Terraform 0.14 having released](https://github.com/hashicorp/terraform/releases/tag/v0.14.0), this project needs to be updated to work with Terraform 0.13.

## Motivation

Terraform 0.13 added functionality to make modules "first-class citizens" of Terraform development. The [release notes](https://github.com/hashicorp/terraform/releases/tag/v0.13.0) have more specific information. Given the reliance on modules in this project, this may prove beneficial. Additionally it is good if we aren't too far behind in Terraform versions so we see regular updates.

**Comment by dav3r** [comment]
This issue is directly related to https://github.com/cisagov/cool-system/issues/94.

**Comment by mcdonnnj** [comment]
Closed by #336.

**Comment by mcdonnnj** [comment]
Closed by #336.
