### ISSUE TITLE
rules.ncats.cyber.dhs.gov should be renamed

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cyhy_amis#309]
# 🚀 Feature Proposal #

Our group is no longer called NCATS, so the https://rules.ncats.cyber.dhs.gov site should be given a new hostname that does not include the name NCATS: `rules.vm.cyber.dhs.gov`.  We should also add a redirect from `rules.ncats.cyber.dhs.gov` to the new site.

See also:
* #284
* #308 

## Motivation ##

We have discontinued the use of the NCATS name almost everywhere else.

**Comment by climber-girl** [comment]
Update on the name change: it sounds like the URL will now be `rules.vm.cyber.dhs.gov` as it makes more sense considering we'll have non-COOL IPs such as those for the Qualys web app scanners.

Actions for this change include:

- [x] Create a new DNS A record for rules.vm.cyber.dhs.gov
- [x] Replace the current A record for rules.ncats.cyber.dhs.gov with a CNAME (alias) that points to rules.vm.cyber.dhs.gov
