### ISSUE TITLE
Lock down metadata service

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cyhy_amis#312]
# 🚀 Feature Proposal #

The AWS metadata service on the CyHy instances should be locked down.  We don't make use of any AWS agents (e.g. the SSM agent or the EFS agent) on the CyHy instances, so [the metadata service can be disabled](https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-instance-metadata-options.html) once `cloud-init` has completed its foo.

We should also configure the metadata service at boot by setting [the following Terraform options](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#metadata-options):
* HTTP endpoint enabled
* PUT response hop limit set to one
* HTTP tokens required

In some cases it _might_ make sense to [disable the metadata service at instance launch](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#metadata-options), but I'm not certain that is possible.  I think it will interfere with the operation of `cloud-init` at boot time.

## Motivation ##

This increases security.

**Comment by mcdonnnj** [comment]
Fully locking down this service requires all AMIs to be on Debian Buster or newer. The version of `cloud-init` available to Debian Stretch does not support token authentication for IMDSv2.

**Comment by mcdonnnj** [comment]
As of #410 our instances will have the SSM agent so disabling is no longer viable when that is merged.
