### ISSUE TITLE
Update to use the 3.x AWS Provider

### ISSUE THREAD

**Issue by mcdonnnj** [cisagov/cyhy_amis#326]
# 🚀 Feature Proposal

The AWS provider used in this project should be updated to use the `3.x` major version as we use in our other Terraform projects at this point.

## Motivation

The `3.x` version has stabilized and our COOL related projects have already migrated to using this AWS provider version. This project is unable to take advantage of new features because it is still pinned against the `2.x` version.

## Pitch

We should be getting access to new functionality as well as improved functionality and stability on the currently developed version of the AWS provider.

**Comment by dav3r** [comment]
@mcdonnnj - I believe we can close this issue now, thanks to #336.

**Comment by mcdonnnj** [comment]
> 
> 
> @mcdonnnj - I believe we can close this issue now, thanks to #336.

Ahh, you are correct. Apologies I completely forgot to link this issue when we did that PR.
