### ISSUE TITLE
Set instance hostnames to match their private DNS entries

### ISSUE THREAD

**Issue by felddy** [cisagov/cyhy_amis#56]
I'd be nice if the hostnames matched the private DNS.   This will probably involve some cloud-init fu as it seems to be setting the hostname at boot using its own AWS sauce.  

Here's a little ditty that works on the Debian boxes:
```
sudo hostnamectl set-hostname `host \`hostname -I | head -n1\` | awk '{print $5}'`
```

**Comment by jsf9k** [comment]
Backticks are pretty old school.  The preferred syntax these days would be:
```
sudo hostnamectl set-hostname $(host $(hostname -I | head -n1) | awk '{print $5}')
```

The Amazon Linux boxes don't use `systemd` and hence don't have `hostnamectl`.  You have to set the hostname a little differently, but this should work:
```
sudo hostname $(host $(hostname -I | head -n1) | awk '{print $5}')
```

**Comment by dav3r** [comment]
Soon we will not have any Amazon Linux instances left (after we move from Nessus 6 to Nessus 8 with PR #163).  At that point, we should be good to use @jsf9k's syntax, with a little extra sauce to remove the trailing period:
```
sudo hostnamectl set-hostname $(host $(hostname -I | head -n1) | awk '{print substr($5, 1, length($5) - 1)}')
```
