### ISSUE TITLE
Reporter ARN check for ansible is prevents terraform apply

### ISSUE THREAD

**Issue by felddy** [cisagov/cyhy_amis#75]
https://github.com/dhs-ncats/cyhy_amis/blob/3e19bbfc79791808cc8c6af93ac01648a54de3f1/terraform/cyhy_reporter_ec2.tf#L67

`terraform apply` results in this:
```
Error: Error running plan: 1 error(s) occurred:

* module.cyhy_reporter_ansible_provisioner.var.envs: Resource 'aws_instance.cyhy_reporter' does not have attribute 'arn' for variable 'aws_instance.cyhy_reporter.arn'
```

Commenting out this line works around the problem.

**Comment by jsf9k** [comment]
This was removed in 17d04a9a406addab80277fb39e30bd2e7ff22836.
