### ISSUE TITLE
Rotate and compress MongoDB log

### ISSUE THREAD

**Issue by dav3r** [cisagov/cyhy_amis#91]
I don't think this was being done in the past, but we now only have an 8GB volume for our Mongo log, so this could become an issue soon.

Note: It seems that you have to restart the mongo service as part of the log rotation, but I'm not sure why we would need to if we use `copytruncate`.    See https://docs.mongodb.com/manual/tutorial/rotate-log-files/

**Comment by jsf9k** [comment]
I don't see the restarting in that document.  Am I just missing it?

**Comment by dav3r** [comment]
No, I didn't read closely enough.  I saw the kill command, but didn't notice that we just have to send it a SIGUSR1 signal.
