### ISSUE TITLE
Add GeoIP database to cyhy-core ansible

### ISSUE THREAD

**Issue by dav3r** [cisagov/cyhy_amis#92]
Make sure to use the new version that we are licensed for:
https://download.maxmind.com/app/geoip_download?edition_id=GeoIP2-City&license_key=  (get license key from @dav3r or @felddy)

**Comment by mcdonnnj** [comment]
This should now be resolved per https://github.com/cisagov/ansible-role-cyhy-core/pull/7

**Comment by dav3r** [comment]
Thanks @mcdonnnj!
